config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :tweets, only: [:create]
  resources :usernames, only: [:new, :update]
  get :dashboard, to: "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: true, length: { maximum: 280 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  validates :username, uniqueness: { case_sensitive: false }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_to_username_form
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  protected

  def redirect_to_username_form
    return if controller_name == "usernames"
    return unless user_signed_in? && current_user.username.blank?
    redirect_to new_username_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user_tweets = current_user.tweets
    @tweet_bodies = @user_tweets.map(&:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_if_current_user

  def index
  end

  private

  def redirect_if_current_user
    redirect_to dashboard_path if current_user
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to dashboard_path
    else
      flash[:notice] = "something_went_wrong"
      redirect_to dashboard_path
    end
  end


  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  before_action :authenticate_user!
  def new
    
  end

  def update
    if username_params[:username].present? && current_user.update(username_params)
      flash[:notice] = "Username Updated!"
      redirect_to dashboard_path
    else
      flash[:alert] = if username_params[:username].blank?
                        "Please Choose a Username"
                      else
                        current_user.errors.full_messages.join(", ")
                      end
      redirect_to new_username_path
    end
  end

  private
  def username_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <aside class="col d-flex justify-content-center mt-3 navigation text-dark">
      <ul class="list-group list-unstyled w-50">
        <li class="border-0 twitter-link">
          <%= link_to root_path do %>
            <i class="bi bi-twitter"></i>
          <% end %>
        </li>
        <li class="list-group-item border-0 fw-bold rounded-pill">
          <%= link_to root_path, class: "link-dark" do %>
            <i class="bi bi-house me-4"></i>Home
          <% end %>
        </li>
        <li class="list-group-item border-0 fw-bold rounded-pill">
          <%= link_to root_path, class: "link-dark" do %>
            <i class="bi bi-hash me-4"></i>Explore
          <% end %>
        </li>
        <li class="list-group-item border-0 fw-bold rounded-pill">
          <%= link_to root_path, class: "link-dark" do %>
            <i class="bi bi-bell me-4"></i>Notifications
          <% end %>
        </li>
        <li class="list-group-item border-0 fw-bold rounded-pill">
          <%= link_to root_path, class: "link-dark" do %>
            <i class="bi bi-envelope me-4"></i>Messages
          <% end %>
        </li>
        <li class="list-group-item border-0 fw-bold rounded-pill">
          <%= link_to root_path, class: "link-dark" do %>
            <i class="bi bi-bookmark me-4"></i>Bookmarks
          <% end %>
        </li>
        <li class="list-group-item border-0 fw-bold rounded-pill">
          <%= link_to root_path, class: "link-dark" do %>
            <i class="bi bi-person-fill me-4"></i>Profile
          <% end %>
        </li>
        <li>
          <%= button_tag "Tweet", class: "btn btn-primary rounded-pill w-100 mt-3"%>
        </li>
      </ul>
    </aside>
    <div class="col">
      <%= form_with model: Tweet.new, url: tweets_path, local: true do |f| %>
        <%= f.text_field :body %>
        <%= f.submit %>
      <% end %>

      <% @tweet_bodies.each do |text| %>
        <ul>
          <li>
            <%= text %>
          </li>
        </ul>
      <% end %>
    </div>
    <div class="col">Col</div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Hello World</h1>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-outline-primary btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if flash.any? %>
      <%= render 'shared/flashes' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" />
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" />
  </div>
<% end %>

app/views/usernames/new.html.erb
<div class="container w-25 py-5">
  <h2>Set Your Username</h2>
  
  <%= form_with model: current_user, local: true, url: username_path(current_user) do |f| %>
    <div class="mb-3">
      <% f.label :username, class: "form-label" %>
      <%= f.text_field :username, class: "form-control" %>
    </div>

    <%= f.submit "Set Username", class: "btn btn-primary btn-lg" %>
  <% end %>
</div>